---
name: Build Docker Image

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          cd go
          docker build -t temp/build .
      - name: Push docker image
        run: | 
          docker tag temp/build irranggakargo/excellerate:latest
          docker push irranggakargo/excellerate:latest

