---
name: Build Docker Image

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          docker build -t temp/build .
      - name: Push docker image
        run: | 
          docker tag temp/build irranggakargo/excellerate:latest
          docker push irranggakargo/excellerate:latest

