---
name: Run Unit Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Golang test
        run: | 
          cd go
          go test .
