---
name: Build Docker Image

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo Continue here...
